# Generated by Django 5.1.2 on 2024-12-04 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chessapp.chessgame')),
            ],
        ),
    ]
